/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as BlueprintsRouteImport } from './routes/blueprints'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as ContextRouteImport } from './routes/context'
import { Route as DiscussRouteImport } from './routes/discuss'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as GatekeepersRouteImport } from './routes/gatekeepers'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OutputsRouteImport } from './routes/outputs'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ThemeRouteImport } from './routes/theme'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as AdminSectionRouteImport } from './routes/admin_.$section'
import { Route as BlueprintIdRouteImport } from './routes/blueprint.$id'
import { Route as GadgetIdRouteImport } from './routes/gadget.$id'
import { Route as GatekeepersAppIdRouteImport } from './routes/gatekeepers_.$appId'
import { Route as IntegrationsAppIdRouteImport } from './routes/integrations_.$appId'
import { Route as WorkspaceIdRouteImport } from './routes/workspace.$id'
import { Route as AdminChannelsChannelRouteImport } from './routes/admin_.channels.$channel'
import { Route as AdminIntegrationsVendorIdRouteImport } from './routes/admin_.integrations.$vendorId'
import { Route as AdminSkillsSkillNameRouteImport } from './routes/admin_.skills.$skillName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsRoute = BlueprintsRouteImport.update({
  id: '/blueprints',
  path: '/blueprints',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextRoute = ContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussRoute = DiscussRouteImport.update({
  id: '/discuss',
  path: '/discuss',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const GatekeepersRoute = GatekeepersRouteImport.update({
  id: '/gatekeepers',
  path: '/gatekeepers',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OutputsRoute = OutputsRouteImport.update({
  id: '/outputs',
  path: '/outputs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeRoute = ThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSectionRoute = AdminSectionRouteImport.update({
  id: '/admin_/$section',
  path: '/admin/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintIdRoute = BlueprintIdRouteImport.update({
  id: '/blueprint/$id',
  path: '/blueprint/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GadgetIdRoute = GadgetIdRouteImport.update({
  id: '/gadget/$id',
  path: '/gadget/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GatekeepersAppIdRoute = GatekeepersAppIdRouteImport.update({
  id: '/gatekeepers_/$appId',
  path: '/gatekeepers/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsAppIdRoute = IntegrationsAppIdRouteImport.update({
  id: '/integrations_/$appId',
  path: '/integrations/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdRoute = WorkspaceIdRouteImport.update({
  id: '/workspace/$id',
  path: '/workspace/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChannelsChannelRoute = AdminChannelsChannelRouteImport.update({
  id: '/admin_/channels/$channel',
  path: '/admin/channels/$channel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrationsVendorIdRoute =
  AdminIntegrationsVendorIdRouteImport.update({
    id: '/admin_/integrations/$vendorId',
    path: '/admin/integrations/$vendorId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSkillsSkillNameRoute = AdminSkillsSkillNameRouteImport.update({
  id: '/admin_/skills/$skillName',
  path: '/admin/skills/$skillName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apps': typeof AppsRoute
  '/assistant': typeof AssistantRoute
  '/blueprints': typeof BlueprintsRoute
  '/channels': typeof ChannelsRoute
  '/context': typeof ContextRoute
  '/discuss': typeof DiscussRoute
  '/explore': typeof ExploreRoute
  '/gatekeepers': typeof GatekeepersRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/outputs': typeof OutputsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/theme': typeof ThemeRoute
  '/workspaces': typeof WorkspacesRoute
  '/admin/$section': typeof AdminSectionRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/gadget/$id': typeof GadgetIdRoute
  '/gatekeepers/$appId': typeof GatekeepersAppIdRoute
  '/integrations/$appId': typeof IntegrationsAppIdRoute
  '/workspace/$id': typeof WorkspaceIdRoute
  '/admin/channels/$channel': typeof AdminChannelsChannelRoute
  '/admin/integrations/$vendorId': typeof AdminIntegrationsVendorIdRoute
  '/admin/skills/$skillName': typeof AdminSkillsSkillNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apps': typeof AppsRoute
  '/assistant': typeof AssistantRoute
  '/blueprints': typeof BlueprintsRoute
  '/channels': typeof ChannelsRoute
  '/context': typeof ContextRoute
  '/discuss': typeof DiscussRoute
  '/explore': typeof ExploreRoute
  '/gatekeepers': typeof GatekeepersRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/outputs': typeof OutputsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/theme': typeof ThemeRoute
  '/workspaces': typeof WorkspacesRoute
  '/admin/$section': typeof AdminSectionRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/gadget/$id': typeof GadgetIdRoute
  '/gatekeepers/$appId': typeof GatekeepersAppIdRoute
  '/integrations/$appId': typeof IntegrationsAppIdRoute
  '/workspace/$id': typeof WorkspaceIdRoute
  '/admin/channels/$channel': typeof AdminChannelsChannelRoute
  '/admin/integrations/$vendorId': typeof AdminIntegrationsVendorIdRoute
  '/admin/skills/$skillName': typeof AdminSkillsSkillNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apps': typeof AppsRoute
  '/assistant': typeof AssistantRoute
  '/blueprints': typeof BlueprintsRoute
  '/channels': typeof ChannelsRoute
  '/context': typeof ContextRoute
  '/discuss': typeof DiscussRoute
  '/explore': typeof ExploreRoute
  '/gatekeepers': typeof GatekeepersRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/outputs': typeof OutputsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/theme': typeof ThemeRoute
  '/workspaces': typeof WorkspacesRoute
  '/admin_/$section': typeof AdminSectionRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/gadget/$id': typeof GadgetIdRoute
  '/gatekeepers_/$appId': typeof GatekeepersAppIdRoute
  '/integrations_/$appId': typeof IntegrationsAppIdRoute
  '/workspace/$id': typeof WorkspaceIdRoute
  '/admin_/channels/$channel': typeof AdminChannelsChannelRoute
  '/admin_/integrations/$vendorId': typeof AdminIntegrationsVendorIdRoute
  '/admin_/skills/$skillName': typeof AdminSkillsSkillNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apps'
    | '/assistant'
    | '/blueprints'
    | '/channels'
    | '/context'
    | '/discuss'
    | '/explore'
    | '/gatekeepers'
    | '/integrations'
    | '/login'
    | '/outputs'
    | '/profile'
    | '/signup'
    | '/theme'
    | '/workspaces'
    | '/admin/$section'
    | '/blueprint/$id'
    | '/gadget/$id'
    | '/gatekeepers/$appId'
    | '/integrations/$appId'
    | '/workspace/$id'
    | '/admin/channels/$channel'
    | '/admin/integrations/$vendorId'
    | '/admin/skills/$skillName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apps'
    | '/assistant'
    | '/blueprints'
    | '/channels'
    | '/context'
    | '/discuss'
    | '/explore'
    | '/gatekeepers'
    | '/integrations'
    | '/login'
    | '/outputs'
    | '/profile'
    | '/signup'
    | '/theme'
    | '/workspaces'
    | '/admin/$section'
    | '/blueprint/$id'
    | '/gadget/$id'
    | '/gatekeepers/$appId'
    | '/integrations/$appId'
    | '/workspace/$id'
    | '/admin/channels/$channel'
    | '/admin/integrations/$vendorId'
    | '/admin/skills/$skillName'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apps'
    | '/assistant'
    | '/blueprints'
    | '/channels'
    | '/context'
    | '/discuss'
    | '/explore'
    | '/gatekeepers'
    | '/integrations'
    | '/login'
    | '/outputs'
    | '/profile'
    | '/signup'
    | '/theme'
    | '/workspaces'
    | '/admin_/$section'
    | '/blueprint/$id'
    | '/gadget/$id'
    | '/gatekeepers_/$appId'
    | '/integrations_/$appId'
    | '/workspace/$id'
    | '/admin_/channels/$channel'
    | '/admin_/integrations/$vendorId'
    | '/admin_/skills/$skillName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppsRoute: typeof AppsRoute
  AssistantRoute: typeof AssistantRoute
  BlueprintsRoute: typeof BlueprintsRoute
  ChannelsRoute: typeof ChannelsRoute
  ContextRoute: typeof ContextRoute
  DiscussRoute: typeof DiscussRoute
  ExploreRoute: typeof ExploreRoute
  GatekeepersRoute: typeof GatekeepersRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  OutputsRoute: typeof OutputsRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  ThemeRoute: typeof ThemeRoute
  WorkspacesRoute: typeof WorkspacesRoute
  AdminSectionRoute: typeof AdminSectionRoute
  BlueprintIdRoute: typeof BlueprintIdRoute
  GadgetIdRoute: typeof GadgetIdRoute
  GatekeepersAppIdRoute: typeof GatekeepersAppIdRoute
  IntegrationsAppIdRoute: typeof IntegrationsAppIdRoute
  WorkspaceIdRoute: typeof WorkspaceIdRoute
  AdminChannelsChannelRoute: typeof AdminChannelsChannelRoute
  AdminIntegrationsVendorIdRoute: typeof AdminIntegrationsVendorIdRoute
  AdminSkillsSkillNameRoute: typeof AdminSkillsSkillNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints': {
      id: '/blueprints'
      path: '/blueprints'
      fullPath: '/blueprints'
      preLoaderRoute: typeof BlueprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context': {
      id: '/context'
      path: '/context'
      fullPath: '/context'
      preLoaderRoute: typeof ContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discuss': {
      id: '/discuss'
      path: '/discuss'
      fullPath: '/discuss'
      preLoaderRoute: typeof DiscussRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gatekeepers': {
      id: '/gatekeepers'
      path: '/gatekeepers'
      fullPath: '/gatekeepers'
      preLoaderRoute: typeof GatekeepersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outputs': {
      id: '/outputs'
      path: '/outputs'
      fullPath: '/outputs'
      preLoaderRoute: typeof OutputsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme': {
      id: '/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof ThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/$section': {
      id: '/admin_/$section'
      path: '/admin/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AdminSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprint/$id': {
      id: '/blueprint/$id'
      path: '/blueprint/$id'
      fullPath: '/blueprint/$id'
      preLoaderRoute: typeof BlueprintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gadget/$id': {
      id: '/gadget/$id'
      path: '/gadget/$id'
      fullPath: '/gadget/$id'
      preLoaderRoute: typeof GadgetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gatekeepers_/$appId': {
      id: '/gatekeepers_/$appId'
      path: '/gatekeepers/$appId'
      fullPath: '/gatekeepers/$appId'
      preLoaderRoute: typeof GatekeepersAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations_/$appId': {
      id: '/integrations_/$appId'
      path: '/integrations/$appId'
      fullPath: '/integrations/$appId'
      preLoaderRoute: typeof IntegrationsAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$id': {
      id: '/workspace/$id'
      path: '/workspace/$id'
      fullPath: '/workspace/$id'
      preLoaderRoute: typeof WorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/channels/$channel': {
      id: '/admin_/channels/$channel'
      path: '/admin/channels/$channel'
      fullPath: '/admin/channels/$channel'
      preLoaderRoute: typeof AdminChannelsChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/integrations/$vendorId': {
      id: '/admin_/integrations/$vendorId'
      path: '/admin/integrations/$vendorId'
      fullPath: '/admin/integrations/$vendorId'
      preLoaderRoute: typeof AdminIntegrationsVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/skills/$skillName': {
      id: '/admin_/skills/$skillName'
      path: '/admin/skills/$skillName'
      fullPath: '/admin/skills/$skillName'
      preLoaderRoute: typeof AdminSkillsSkillNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppsRoute: AppsRoute,
  AssistantRoute: AssistantRoute,
  BlueprintsRoute: BlueprintsRoute,
  ChannelsRoute: ChannelsRoute,
  ContextRoute: ContextRoute,
  DiscussRoute: DiscussRoute,
  ExploreRoute: ExploreRoute,
  GatekeepersRoute: GatekeepersRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  OutputsRoute: OutputsRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  ThemeRoute: ThemeRoute,
  WorkspacesRoute: WorkspacesRoute,
  AdminSectionRoute: AdminSectionRoute,
  BlueprintIdRoute: BlueprintIdRoute,
  GadgetIdRoute: GadgetIdRoute,
  GatekeepersAppIdRoute: GatekeepersAppIdRoute,
  IntegrationsAppIdRoute: IntegrationsAppIdRoute,
  WorkspaceIdRoute: WorkspaceIdRoute,
  AdminChannelsChannelRoute: AdminChannelsChannelRoute,
  AdminIntegrationsVendorIdRoute: AdminIntegrationsVendorIdRoute,
  AdminSkillsSkillNameRoute: AdminSkillsSkillNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
